### ISSUE TITLE
(pass-winmenu) Change gpg dependency

### ISSUE THREAD

**Issue by AeliusSaionji** [majkinetor/au-packages#112]
https://chocolatey.org/packages/pass-winmenu

The current dependency on gpg4win-vanilla is creating problems.

Gpg4win-vanilla hasn't been updated since 2017. I realize gpg itself hasn't seen an update since then either, however the latest gpg4win package includes a newer pinentry dialog and agent.

This is important because pass-winmenu offers to edit the configuration for gpg agent, and the generated config just does not work for whatever ancient version gpg4win-vanilla is giving us.

Also, the ancient pinentry dialog from gpg4win-vanilla is buggy on the latest builds of win10. It no longer grabs focus on 2/3 of my machines and no longer correctly resumes focus back to the original program to which I am typing the password. Thus, it is broken, and it is breaking the functionality of pass-winmenu.

The chocolatey package `gpg4win` is up to date and everything works as expected, and pass-winmenu was built with that in mind.

Please drop the dependency for `gpg4win-vanilla` and add a dependency to `gpg4win`.

Thank you!

**Comment by majkinetor** [comment]
@wget has similar arguments a year ago.

I used this dependency as (besides being the current one back then) is as small as it can get. AFAIK *vanilla* and *light* variants are no longer produced and `gpg4win` installs also kleopatra and some other stuff which are not needed for `pass-winmenu`.

> This is important because pass-winmenu offers to edit the configuration for gpg agent, and the generated config just does not work for whatever ancient version gpg4win-vanilla is giving us.

Didn't know about this, I used this tool initially but later implemented my own as I needed it also to work with symmetric encryption (via passphrase). 

Not sure what to do ATM.

**Comment by AeliusSaionji** [comment]
The intended dependency includes extra gunk, yes. However, as mentioned, last week the old pinentry interface has effectively broken on two separate devices. I'm sure the bug will start happening for others.

It's unfortunate that the minimal package is no longer maintained by gpg4win, but really we shouldn't be offering outdated packages as new, especially when it's encryption related.

**Comment by majkinetor** [comment]
One option would be *us* to provide vanilla installer. I guess it could simply install `gpg4win`, copy the vanilla gpg stuff and manually install agent service.

**Comment by AeliusSaionji** [comment]
That could be an option, but every time I've brought up the subject of "chocolatey build/chocolatey customized", the idea was generally not accepted.

**Comment by majkinetor** [comment]
I accept it :)

**Comment by majkinetor** [comment]
FYI, there is also a pass-winmenu that includes gpg

* https://github.com/Baggykiin/pass-winmenu/releases

The no-gpg version is something I requested in order to reduce package size and also integrate well will any existing installations.


/cc @Baggykiin

**Comment by majkinetor** [comment]
BTW, the upstream could offer solution too, but providing configuration of agent that takes version into account.

**Comment by AeliusSaionji** [comment]
> Also, is this problem perhaps related to latest release 1.9.1:

I don't believe so- the fix is about not overwriting an existing config, I think.

**Comment by Baggykiin** [comment]
> I don't believe so- the fix is about not overwriting an existing config, I think.

That's correct, it contained a bug causing it to overwrite any lines which did not contain valid configuration keys (including comment lines). Free to submit an issue upstream for the problem you're encountering. Since it's an old version of `gpg-agent` I cannot guarantee I will be able to support it, but I can look into it at the very least.


@majkinetor it may also worth considering that the GPG project itself is also providing a Windows distribution, separate from Gpg4Win (See the [download](https://gnupg.org/download/index.html#binary) page: "Simple installer for the current GnuPG").

This is the version that was originally packaged with pass-winmenu, before I switched over to Gpg4Win. The reason for that was that `gpg-agent` had a nasty bug causing it to freeze up completely at a somewhat regular interval, and that bug was not present on the Gpg4Win version.

It seems like https://chocolatey.org/packages/gnupg-modern uses that distribution as its upstream. You could try switching your dependency to that package instead, just be aware that the bug I mentioned may still exist.

**Comment by majkinetor** [comment]
OK, I will change dependency to Gpg4Win then since that is what is used upstream.
