### ISSUE TITLE
(less) Add install parameters /ConfigurePowerShell6 /ConfigurePowerShell7

### ISSUE THREAD

**Issue by rkeithhill** [majkinetor/au-packages#115]
What this option would do is create an environment variable that for PowerShell 7, will cause it to use `less` instead of `more` for paging help.  The environment variable I recommend is this:
```
PAGER = 'less "-PsPage %db?B of %D:.\. Press h for help or q to quit\.$"'
```
This will result in the following useful prompt when help is piped through less:
![image](https://user-images.githubusercontent.com/5177512/60773721-a3960f00-a0c6-11e9-875a-a3db0173d02b.png)

The bummer is that this value of `PAGER` causes problems with PS Core v6.  So for `/ConfigurePowerShell6`, I'd recommend using just `PAGER = 'less'`.  

Finally, PS 7 preview.1 also has the same issue that PS Core 6 has.  But that issue has been fixed (by me) and should be in preview.2 due out later this month.  

I'm not sure those are the best parameter names.  They should be mutually exclusive since you can only set the PAGER env var once unless you wanted to get into modifying PowerShell profiles (messy).

**Comment by majkinetor** [comment]
That sounds confusing. 

I would rather use simple parameter such as `/DefaultPager` that would adapt on its own if needed - it could recognize posh version, maybe it could also also set some vars for other shells. Not sure if that is easily possible tho, chocolatey hosts its own posh by default, so its version details may not represent those of the system. You could also have multiple versions (5,6) at the same time.

Going with simple `less` in each case might be hence better, particularly since that warning is cosmetic ? Thoughts ?

**Comment by majkinetor** [comment]
Added `/DefaultPager` param, points to less without any arguments for now.
