### ISSUE TITLE
Duplicate packages

### ISSUE THREAD

**Issue by pauby** [majkinetor/au-packages#123]
Both this `Invoke-Build' package and the [`InvokeBuild`](https://chocolatey.org/packages/invokebuild) package are duplicates. There is an issue raised at https://github.com/pauby/ChocoPackages/issues/44.

I don't think it's constructive as to whos package is right or wrong so what I'd like to suggest is what I mentioned on the issue above - adding the functionality to this package to allow both PowerShell Core and Windows PowerShell modules to be installed.

Is there any mileage in adding code around this to here, similar to what is done for [pshtml.powershell](https://github.com/pauby/chocopackages/tree/master/automatic/pshtml.powershell)?

**Comment by majkinetor** [comment]
Sure

**Comment by majkinetor** [comment]
Package works correctly in pwsh7.

**Comment by gep13** [comment]
@majkinetor when this issue was opened, the hope was that this package could be updated to include both the PowerShell Core and Windows PowerShell modules.  This would allow deprecating of the other Invoke-Build package, to prevent the need for duplicate packages.  Is this something that you are not interested in proceeding with?

**Comment by majkinetor** [comment]
It works with core. I use it all the time on pwsh 7. So there is nothing to do.
