### ISSUE TITLE
Total Commander plugins proposals

### ISSUE THREAD

**Issue by QuAzI** [majkinetor/au-packages#217]
Please add 7zip, MarkdownViewer, SVGView, PDFView

**Comment by majkinetor** [comment]
Please give links and I will see what I can do.

**Comment by QuAzI** [comment]
- 7zip - https://ghisler.fileburst.com/plugins/wcx_7zip.zip - official 7zip plugin from https://www.ghisler.com/plugins.htm
- MarkdownViewer - [rg-software/wlx-markdown-viewer](https://github.com/rg-software/wlx-markdown-viewer)
- SVGView - https://totalcmd.net/plugring/svgview.html but link is broken. But you have some plugins from same author [Progman13](https://totalcmd.net/authors/1196678.html)
- ~~PDFView - https://totalcmd.net/plugring/pdfview.html~~ looks a bit broken now

**Comment by majkinetor** [comment]
7zip is very old plugin and TC also already does unpacking. Moreover, I tried it now and it doesn't seem to work - it doesn't show in the TC pack list

![image](https://user-images.githubusercontent.com/85767/174328937-e0f5af32-6893-4594-8449-499a416a6fab.png)

![image](https://user-images.githubusercontent.com/85767/174329344-e45001e7-31d0-4d43-972a-91188ebf242f.png)

It shows in Double Cmd list, however, it already has 7z internally (as shown above the combo box)

![image](https://user-images.githubusercontent.com/85767/174328865-a277450b-282a-420e-b424-2b36b812298b.png)

Progman stuff are broken, as domain is non existent so currently on his choco packages work as they contain the plugin independently.


That leaves markdown viewer. Since it doesn't have license stated, you will have to contact the author to allow redistribution as a Chocolatey package and provide proof here. As an example 7zip has License.txt inside the archive which can be used.

**Comment by QuAzI** [comment]
OMG, yeah. You right. I have a bit never version from http://totalcmd.net/plugring/7zip_plugin.html
And it works with TC 10.50b8 fine
![image](https://user-images.githubusercontent.com/1897605/174331843-31b78971-a312-4d50-bee6-7ea0357f69b4.png)

**Comment by majkinetor** [comment]
OK, since I already created it and it works for you here it is for 7zip:

https://community.chocolatey.org/packages/tcp-7zip

You will have to wait for approval, but you can test it asap by using:

`choco install tcp-7zip --version 0.7.6.6`
