### ISSUE TITLE
winget support

### ISSUE THREAD

**Issue by QuAzI** [majkinetor/au-packages#218]
Is there any way to use winget for install Total Commander plugins?

**Comment by majkinetor** [comment]
No there isn't at this moment and I doubt its possible at this moment given that it requires custom scripting. 

I plan to get into winget so I will know more in the future. If/when it becomes possible I will probably move it there.

**Comment by majkinetor** [comment]
One of the problems of winget is that it currently doesn't allow packages to contain software. Which is the major problem since then you depend on the network. They added portable file in latest release, but allow just single exe, so if that feature extends it could be used. 

Otherwise, if totalcmd.net doesn't work you will not be able to get plugins. You can currently depend on it on chocolatey - stuff will always work, and if choco goes out of business you can still get packages from my GitHub releases.
