### ISSUE TITLE
NirLauncher "Waiting for maintainer"

### ISSUE THREAD

**Issue by ImportTaste** [majkinetor/au-packages#232]
Two newest versions are stuck in the queue, apparently waiting for you to do something:

![image](https://user-images.githubusercontent.com/53661808/233432675-e6566d1b-db28-45a3-94b8-1a549a92de10.png)

**Comment by majkinetor** [comment]
Not for me. Choco admins require I request virus total exclusion for each version. I wont obviosly do that as it defeats purpose of automatic package. So until they fix their process consider the package abandoned.

**Comment by majkinetor** [comment]
Note that I provided Note as choco admins requested, but that was apparently not enough:

![image](https://user-images.githubusercontent.com/85767/233446451-15b1d944-df2f-4a6a-aece-cf271c004869.png)

I remember they said to me its because of "the problems in their process" but I CBB to find it now among comments on some version.

**Comment by majkinetor** [comment]
> so it just seems to make sense to mark the project as such.

I don't want it to look as my failure, my packages always work until choco admins get involved. 

I guess its better to support techinical failure rather then human :)

**Comment by majkinetor** [comment]
Its excluded from verification now, it seems.
